### ISSUE TITLE
Supported models

### ISSUE THREAD

**Issue by Camperor** [Svirusx/SM-G781B_S20_FE_5G#1]
Thanks for making this kernel! I see it supports the SM-G781B but does it support any other models like the SM-G780 series (non-5G version of the S20 FE) or any of the Snapdragon versions of the regular Galaxy S20/S20+/Note 20, etc?

**Comment by Svirusx** [comment]
Maybe in future, i have only SM-G781B so this kernel is tested. Without test device i can't test patches and it is more difficult to make support for Nethunter but it isn't impossible.
