### ISSUE TITLE
S20 fe 5g got one ui 3.1

### ISSUE THREAD

**Issue by prasadsince1999** [Svirusx/SM-G781B_S20_FE_5G#2]
![Screenshot_20210623-081030_Settings](https://user-images.githubusercontent.com/64558576/123026894-8dd89c00-d3fa-11eb-9f32-e93c371b9c9d.jpg)
S20 fe 5g got one ui 3.1 so I wait for new update or flash your kali nethunter kernel 3.0 or you give update 3.1 in kali nethunter official page I want to volunteer for this s20 fe 5g nethunter project 🤗

**Comment by Svirusx** [comment]
My kernel support one ui 3.1
![Screenshot_20210627-092448_Settings](https://user-images.githubusercontent.com/45526199/123536283-aeba2d80-d729-11eb-8b67-781c3fe8ee3e.jpg)

**Comment by prasadsince1999** [comment]
@Svirusx  😭 i buy S20FE 5G for your kernel support can you please tell you have same phone means you give kernel update for long time like oneplus one nethunter kernel i wants to surety S20FE 5G worth or not ( please reply )

**Comment by Svirusx** [comment]
S20 FE 5g is my daily driver smartphone. How long i use it have support. When i switch to another smartphone then i make support further to S20 FE 5g but mostly for new Nethunter features when they appear.

**Comment by prasadsince1999** [comment]
![Screenshot_20210709-064842_Samsung Internet](https://user-images.githubusercontent.com/64558576/125009271-d68e8700-e081-11eb-86b0-81c6105893a9.jpg)
One ui 3.1 source code is now available

**Comment by sabbirkhankali** [comment]
Sir please build Galaxy M20 nethunter kernal
