### ISSUE TITLE
G780G support

### ISSUE THREAD

**Issue by sienikam** [Svirusx/SM-G781B_S20_FE_5G#3]
Hello,

Is that kernel support G780G model ? (this is S20FE without 5G based on Snapdragon)
Is packet injection working on internal wifi chipset? 

Thanks.

**Comment by Svirusx** [comment]
Packet injection does not work with internal wifi chipset. It might support G780G if kernel source are not too different, you could test it but no warranty for working. I do not have G780G so i can not test it.
