### ISSUE TITLE
Is this a gki kernel build?

### ISSUE THREAD

**Issue by cyrus104** [Svirusx/SM-G781B_S20_FE_5G#4]
I'm looking to duplicate your work for the Google Pixel 6 and 6 Pro. While I have some experience building kernels for computers (x86/64) and single board computers (arm/arm64/imx), this will be the first time I worked on a phone build.

With that out of the way, I'm fairly new to GKI. The google devices, have their kernel source available. I am looking to see what I need to do special. I'm also trying to find the def_config file for the Pixel devices too. I wanted to see if you had a couple of minutes to help point me in the right direction. As for the full nethunter build, I'm planning to use the ProtonAOSP Rom.

https://source.android.com/setup/build/building-kernels

**Comment by Svirusx** [comment]
This kernel is only for S20 FE 5G, you need to get kernel source for Google Pixel 6 but most of time to compile it you need special patches, maybe you can use anyother custom kernel which is made for Google Pixel 6 and try compile it for you. When you success with it you can go further and add some nethunter features. e.q. https://forum.xda-developers.com/t/kernel-blu_spark-r49-a12.4370811/
