### ISSUE TITLE
Casual Advise for running docker and use phone as server

### ISSUE THREAD

**Issue by Morakhiyasaiyam** [Svirusx/SM-G781B_S20_FE_5G#6]
Hey ,
I am running docker in my k20 pro with android 12L
And it is working good 
But i have some flow with it
Like device is heating and termination of containers and termux it self when not in use and in background process
Except this everything working like charm
But k20 pro is lacking hdmi out
So i am curious how your s20 working with docker and did you used your phone with dex support with any large 4k display and used it as server for mainly everything for home-server 
I am thinking to buy used cheap galaxy note10 or s10 with 12 gb ram and 256 gb or 512 gb storage for running home-server with connecting to my 4k tv and also for gaming on large tv 
Can you confirm is it worth ?

**Comment by Svirusx** [comment]
I used my S20 FE 5G with HP Docking station and 3 monitors it work not bad but here is not possible to set extended screen, i didn't used 4k display, docker was only for gitea but now i don't need to have gitea server on my smartphone. I can't give you any recommendation i don't switch my smartphones often. I switched from S7 to S20.

**Comment by Morakhiyasaiyam** [comment]
Did you build docker image on phone or desktop for gitea? Because when i start to build any image on phone it hangs after executing some commands and then crash & rebooting device!
