### ISSUE TITLE
How to build kernel files for SM-N986B (EXYNOS)

### ISSUE THREAD

**Issue by rapbando** [Svirusx/SM-G781B_S20_FE_5G#7]
Hi,

do you know if it is possible to build the Nethunter kernel files for SM-N986B?

**Comment by Svirusx** [comment]
Maybe it could be possible but you need to search how it's not soo simple. If you want to do yourself i recommend to look at XDA for your smartphone custom roms and kernels if they are here. From source code of another developer is easier to make Nethunter kernel than from samsung source code which mostly is not bootable (need fixes).
