### ISSUE TITLE
S22 kernel build problem 

### ISSUE THREAD

**Issue by alfredx98** [Svirusx/SM-G781B_S20_FE_5G#9]
there has two developer help me to build s22 
sm s9010 snapdragon kernel,but it keep bootlooping .both of them don't know how to fix that problem.Can u help me to build it.if u can handle that problem I'll buy you a coffee for your helping.

**Comment by Svirusx** [comment]
CONFIG_PSTORE=y if you don have it in defconfig
after "bootloop" boot to TWRP and try getting pstore logs those logs are like dmesg
adb pull /sys/fs/pstore 

Maybe you can find here what is problem.
